Benjamin Wilson & Madison Mejia
Prelab 2
September 6, 2021

Script started on 2021-09-06 19:45:38-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="188" LINES="11"]
]0;ben@Clover-VirtualBox: ~/cse113/prelab2[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/prelab2[00m$ gcc -g -Wall ch5_pp7.c -o ch5_pp7
]0;ben@Clover-VirtualBox: ~/cse113/prelab2[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/prelab2[00m$ ./ch5_pp7
Enter four different integers with only one space between them: 40 5067 -1 3

Smallest: -1
Largest: 5067
]0;ben@Clover-VirtualBox: ~/cse113/prelab2[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/prelab2[00m$ ./ch5_pp7
Enter four different integers with only one space between them: 400 2 4 6

Smallest: 2
Largest: 400
]0;ben@Clover-VirtualBox: ~/cse113/prelab2[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/prelab2[00m$ ./ch5_pp7 [K
Enter four different integers with only one space between them: 99999 -76 999999 5

Smallest: -76
Largest: 999999
]0;ben@Clover-VirtualBox: ~/cse113/prelab2[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/prelab2[00m$ exit
exit

Script done on 2021-09-06 19:48:22-06:00 [COMMAND_EXIT_CODE="0"]
